export const ROUTES = {
  LANDING: "/landing",
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  PROBLEM: "/problem/:id",
  ADD_PROBLEM: "/add-problem",
  UPDATE_PROBLEM: "/update-problem/:id",
  PROFILE: "/profile",
  COLLABORATIVE_EDITOR: "/collaborative-editor",
  MY_ACTIVITIES: "/my-activities",
  QUIZ: "/quiz",
  NEWQUIZ: "/quiz/new",
  PRICING: "/pricing",
  BILLING: "/billing",
};
